In [1]:
import torch

In [3]:
X = torch.tensor(
    [
        [0.11, 0.09], [0.01, 0.02], [0.98, 0.91],
        [0.12, 0.21], [0.98, 0.99], [0.85, 0.87],
        [0.03, 0.14], [0.55, 0.45]
    ]
)

In [5]:
print('Shape of the matrix is: {}'.format(X.shape))

Shape of the matrix is: torch.Size([8, 2])


In [6]:
first_element = X[0, 0]
first_element

tensor(0.1100)

In [7]:
row_0 = X[0, :]
row_1 = X[1, 0:2]

In [9]:
row_1

tensor([0.0100, 0.0200])

In [10]:
column_0 = X[:, 0]
column_1 = X[:, 1]

In [11]:
column_1

tensor([0.0900, 0.0200, 0.9100, 0.2100, 0.9900, 0.8700, 0.1400, 0.4500])

In [14]:
first_3_training_examples = X[:3, ]
first_3_training_examples

tensor([[0.1100, 0.0900],
        [0.0100, 0.0200],
        [0.9800, 0.9100]])

In [15]:
tensor = torch.rand((5, 5, 3))

In [16]:
tensor

tensor([[[0.7292, 0.6640, 0.8984],
         [0.6424, 0.0054, 0.6714],
         [0.7395, 0.3256, 0.8304],
         [0.0653, 0.4802, 0.7203],
         [0.1808, 0.1040, 0.4352]],

        [[0.5276, 0.9262, 0.4828],
         [0.4380, 0.3802, 0.2100],
         [0.4244, 0.3562, 0.7351],
         [0.5862, 0.8580, 0.2319],
         [0.8254, 0.3029, 0.9074]],

        [[0.0952, 0.6888, 0.2561],
         [0.5717, 0.0918, 0.1049],
         [0.5357, 0.5755, 0.0105],
         [0.9329, 0.3754, 0.4517],
         [0.3292, 0.9300, 0.0961]],

        [[0.8063, 0.2289, 0.1417],
         [0.2932, 0.2113, 0.7237],
         [0.7114, 0.3214, 0.2164],
         [0.3038, 0.8151, 0.0240],
         [0.2302, 0.9180, 0.3264]],

        [[0.5586, 0.9223, 0.3527],
         [0.5965, 0.2697, 0.4561],
         [0.3462, 0.4444, 0.5632],
         [0.7113, 0.8629, 0.7076],
         [0.2911, 0.0214, 0.0229]]])

In [17]:
I49 = torch.tensor(
    [
        [0, 8, 16, 24, 32, 40, 48, 56, 64],
        [64, 72, 80, 88, 96, 104, 112, 120, 128],
        [128, 136, 144, 152, 160, 168, 176, 184, 192],
        [192, 200, 208, 216, 224, 232, 240, 248, 255]
    ],
)

In [18]:
I49

tensor([[  0,   8,  16,  24,  32,  40,  48,  56,  64],
        [ 64,  72,  80,  88,  96, 104, 112, 120, 128],
        [128, 136, 144, 152, 160, 168, 176, 184, 192],
        [192, 200, 208, 216, 224, 232, 240, 248, 255]])

In [19]:
I49 = torch.stack(
    [
        torch.arange(0, 72, 8), 
        torch.arange(64, 136, 8),
        torch.arange(128, 200, 8), 
        torch.arange(192, 264, 8),
    ]
)

In [20]:
I49

tensor([[  0,   8,  16,  24,  32,  40,  48,  56,  64],
        [ 64,  72,  80,  88,  96, 104, 112, 120, 128],
        [128, 136, 144, 152, 160, 168, 176, 184, 192],
        [192, 200, 208, 216, 224, 232, 240, 248, 256]])

In [22]:
I49.shape[0], I49.shape[1]

(4, 9)

In [21]:
I49_t = torch.transpose(I49, 0, 1)

for i in range(0, I49.shape[0]):
    for j in range(0, I49.shape[1]):
        assert I49[i][j] == I49_t[j][i]

In [23]:
assert torch.allclose(I49_t, I49.T, 1e-5)

In [24]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a_dot_b = torch.dot(a, b)
print('Dot product of these two vectors is: {}'.format(a_dot_b))

Dot product of these two vectors is: 32


In [25]:
# Dot product of perpendicular vectors is zero
vx = torch.tensor([1, 0]) # a vector along X-axis
vy = torch.tensor([0, 1]) # a vector along Y-axis
print('Example dot product of orthogonal vectors: {}'.format(torch.dot(vx, vy)))

Example dot product of orthogonal vectors: 0


In [26]:
X = torch.tensor(
    [
        [0.11, 0.09], 
        [0.01, 0.02], 
        [0.98, 0.91], 
        [0.12, 0.21],
        [0.98, 0.99], 
        [0.85, 0.87], 
        [0.03, 0.14], 
        [0.55, 0.45],
        [0.49, 0.51], 
        [0.99, 0.01], 
        [0.02, 0.89], 
        [0.31, 0.47],
        [0.55, 0.29], 
        [0.87, 0.76], 
        [0.63, 0.24]
    ]
)

In [27]:
w = torch.rand((2, 1))
b = 5.0

In [29]:
w

tensor([[0.8222],
        [0.6739]])

In [30]:
y = torch.matmul(X, w) + b
y

tensor([[5.1511],
        [5.0217],
        [6.4190],
        [5.2402],
        [6.4729],
        [6.2851],
        [5.1190],
        [5.7554],
        [5.7466],
        [5.8207],
        [5.6162],
        [5.5716],
        [5.6476],
        [6.2275],
        [5.6797]])

In [31]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])
B = torch.tensor([[7, 8], [9, 10]])

In [32]:
C = torch.matmul(A, B)

In [36]:
w = torch.tensor([1, 2, 3])
x = torch.tensor([4, 5, 6])
assert torch.dot(w, x) == torch.matmul(w.T, x)

In [37]:
assert torch.all(torch.matmul(A, B).T == torch.matmul(B.T, A.T))

In [38]:
assert torch.all(torch.matmul(A.T, x).T == torch.matmul(x.T, A))

In [39]:
def determinant(A):
    return torch.linalg.det(A)

def inverse(A):
    return torch.linalg.inv(A)

In [60]:
A = torch.tensor([[2, 3], [3, 2]], dtype=torch.float)
A

tensor([[2., 3.],
        [3., 2.]])

In [61]:
A_inv = inverse(A)
A_inv

tensor([[-0.4000,  0.6000],
        [ 0.6000, -0.4000]])

In [62]:
I = torch.eye(2)
I

tensor([[1., 0.],
        [0., 1.]])

In [63]:
assert torch.allclose(torch.matmul(A, A_inv), I, 1e-1)
assert torch.allclose(torch.matmul(A_inv, A), I, 1e-5)

In [64]:
assert torch.all(torch.matmul(I, A) == A)
assert torch.all(A == torch.matmul(A,I))

In [66]:
B = torch.tensor([[1, 1], [2, 2]], dtype=torch.float)
B

tensor([[1., 1.],
        [2., 2.]])

In [67]:
try:
    B_inv = inverse(B)
except RuntimeError as e:
    print('B cannot be inverted: {}'.format(B, e))

B cannot be inverted: tensor([[1., 1.],
        [2., 2.]])


In [ ]:
def pseudo_inverse(A):
    return torch.matmul(torch.linalg.inv(torch.matmul(A.T, A)), A.T)