In [14]:
import torch
import numpy as np

In [3]:
v = torch.tensor(
    [
        0.11,
        0.01,
        0.98,
        0.12,
        0.98,
        0.85,
        0.03,
        0.55,
        0.49,
        0.99,
        0.02,
        0.31,
        0.55,
        0.87,
        0.63,
    ],
    dtype=torch.float64,
)

In [4]:
v

tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)

In [5]:
first_element = v[0]
third_element = v[2]

In [6]:
first_element

tensor(0.1100, dtype=torch.float64)

In [7]:
third_element

tensor(0.9800, dtype=torch.float64)

In [8]:
last_element = v[-1]
second_last_element = v[-2]

In [9]:
last_element

tensor(0.6300, dtype=torch.float64)

In [10]:
second_to_fifth_elements = v[1:4]

In [11]:
second_to_fifth_elements

tensor([0.0100, 0.9800, 0.1200], dtype=torch.float64)

In [13]:
num_elements_in_v = len(v)
num_elements_in_v

15

In [15]:
u = np.array(
    [
        0.11,
        0.01,
        0.98,
        0.12,
        0.98,
        0.85,
        0.03,
        0.55,
        0.49,
        0.99,
        0.02,
        0.31,
        0.55,
        0.87,
        0.63,
    ]
)

In [16]:
u = torch.from_numpy(u)

In [17]:
u

tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)

In [18]:
diff = v.sub(u)

In [19]:
diff

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=torch.float64)

In [20]:
u1 = u.numpy()

In [21]:
u1

array([0.11, 0.01, 0.98, 0.12, 0.98, 0.85, 0.03, 0.55, 0.49, 0.99, 0.02,
       0.31, 0.55, 0.87, 0.63])